import axios from 'axios'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'

import { ChangeEvent, useState } from 'react'

const Home: NextPage = () => {
    const router = useRouter()

    const [query, setQuery] = useState<string | null>(null)
    const [results, setResults] = useState<any[] | null>(null)

    const onInputChange = (event: ChangeEvent<HTMLInputElement>) => {
        setQuery(event.target.value.length ? event.target.value : null)
    }

    const onSearchClick = async () => {
        if (query) {
            const response = await axios.get(`/api/search?q=${encodeURIComponent(query)}`)

            const collections = response.data.collections

            setResults(collections.length ? collections : [])
        }
    }

    return (
        <>
            <Head>
                <title>D100</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <input onChange={onInputChange} />
                {results == null ? null : results.length ? (
                    <ul>
                        {results.map((result: any) => (
                            <li key={result.id} onClick={() => router.push(`/${result.id}`)}>
                                {result.name}
                            </li>
                        ))}
                    </ul>
                ) : (
                    <span>No results</span>
                )}
                <button disabled={query == null || query.length === 0} onClick={onSearchClick}>
                    Search
                </button>
            </main>
        </>
    )
}

export default Home
